// <auto-generated />
namespace demo03_ASPNETIndentity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class DateBirth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DateBirth));
        
        string IMigrationMetadata.Id
        {
            get { return "201312060407464_DateBirth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
