//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo02_Scaffolding
{
    using System;
    using System.Collections.Generic;
    
    public partial class provision_marker_dss
    {
        public int object_id { get; set; }
        public int owner_scope_local_id { get; set; }
        public Nullable<int> provision_scope_local_id { get; set; }
        public long provision_timestamp { get; set; }
        public int provision_local_peer_key { get; set; }
        public Nullable<int> provision_scope_peer_key { get; set; }
        public Nullable<long> provision_scope_peer_timestamp { get; set; }
        public Nullable<System.DateTime> provision_datetime { get; set; }
        public Nullable<int> state { get; set; }
        public byte[] version { get; set; }
    }
}
