//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo02_Scaffolding
{
    using System;
    using System.Collections.Generic;
    
    public partial class scope_info_dss
    {
        public int scope_local_id { get; set; }
        public System.Guid scope_id { get; set; }
        public string sync_scope_name { get; set; }
        public byte[] scope_sync_knowledge { get; set; }
        public byte[] scope_tombstone_cleanup_knowledge { get; set; }
        public byte[] scope_timestamp { get; set; }
        public Nullable<System.Guid> scope_config_id { get; set; }
        public int scope_restore_count { get; set; }
        public string scope_user_comment { get; set; }
    }
}
